import type { SourceTable } from './types.js';

export const SOURCE_COLUMNS: Readonly<Record<SourceTable, readonly string[]>> = {
	createdTests: [
		'genTestID',
		'testModelID',
		'genDate',
		'course_type',
		'length',
		'instructorID',
		'testPassword',
		'overridePassword'
	],
	EO: ['eo_id', 'spo_id', 'eo_no', 'element_name'],
	instructors: ['instructorID', 'employeeNo', 'firstName', 'lastName', 'password', 'admin'],
	logins: ['loginID', 'password', 'override', 'genTestID', 'attemptCount', 'studentEmpNo'],
	questions: [
		'questionID',
		'category',
		'subcategory',
		'spo_id',
		'eo_id',
		'variant_id',
		'type',
		'correct_answer',
		'alt_correct_answer',
		'last_correct_answer',
		'ans_x',
		'ans_y',
		'ans_z',
		'question_a',
		'question_b'
	],
	SPO: ['spo_id', 'tpo_id', 'spo_number', 'spo_name'],
	stamp: ['genDate', 'stampin'],
	studentTestRecords: [
		'recordID',
		'employeeNo',
		'firstName',
		'lastName',
		'classDate',
		'testDate',
		'instructorID',
		'syllabus',
		'qualCode',
		'genTestID',
		'retrain',
		'result',
		'score'
	],
	testModel: [
		'test_model_id',
		'variant_id',
		'spo_id',
		'count',
		'eo_id',
		'course_type',
		'test_length',
		'name'
	],
	testResults: ['resultID', 'employeeNo', 'genTestID', 'questionID', 'correct'],
	test_info: ['testID', 'modelID', 'date'],
	test_model: [
		'testID',
		'course_type',
		'length',
		'air_condition',
		'acft_gen',
		'apu',
		'autopilot',
		'crew_awareness',
		'elec',
		'emerg_equip',
		'fire_prot',
		'flt_control',
		'fuel',
		'hydraulics',
		'ice_rain_prot',
		'ldg_gear_brk',
		'lighting',
		'limitations',
		'oxy',
		'performance',
		'pneum',
		'powerplant',
		'pressurization',
		'profiles',
		'radar',
		'stall_prot',
		'mandatory'
	],
	TPO: ['tpo_id', 'tpo_number', 'tpo_name'],
	usedQuestions: [
		'genTestID',
		'questionID',
		'type',
		'spo_id',
		'subcategory',
		'questionText',
		'a',
		'b',
		'c',
		'd',
		'answerKey'
	],
	variant: ['variant_id', 'variant_name']
};

export const SOURCE_DISPOSITIONS: Readonly<Record<SourceTable, string>> = {
	TPO: 'migrate',
	SPO: 'migrate',
	EO: 'migrate',
	variant: 'migrate',
	questions: 'migrate',
	test_model: 'template_source',
	testModel: 'template_source',
	createdTests: 'aggregate',
	usedQuestions: 'aggregate_or_quarantine',
	studentTestRecords: 'aggregate',
	testResults: 'aggregate',
	instructors: 'exclude',
	logins: 'exclude',
	stamp: 'exclude',
	test_info: 'exclude'
};
